// This file is part of Notepad++ project
// Copyright (C)2025 Don HO <don.h@free.fr>
// Minimal subset for HL7 plugin

#pragma once
#include <windows.h>

enum LangType { L_TEXT, L_PHP, L_C, L_CPP, L_CS, L_OBJC, L_JAVA, L_RC,
    L_HTML, L_XML, L_MAKEFILE, L_PASCAL, L_BATCH, L_INI, L_ASCII, L_USER,
    L_ASP, L_SQL, L_VB, L_JAVASCRIPT, L_CSS, L_PERL, L_PYTHON, L_LUA,
    L_TEX, L_FORTRAN, L_BASH, L_FLASH, L_NSIS, L_TCL, L_LISP, L_SCHEME,
    L_ASM, L_DIFF, L_PROPS, L_PS, L_RUBY, L_SMALLTALK, L_VHDL, L_KIX, L_AU3,
    L_CAML, L_ADA, L_VERILOG, L_MATLAB, L_HASKELL, L_INNO, L_SEARCHRESULT,
    L_CMAKE, L_YAML, L_COBOL, L_GUI4CLI, L_D, L_POWERSHELL, L_R, L_JSP,
    L_COFFEESCRIPT, L_JSON, L_GOLANG,
    L_TYPESCRIPT, L_JSON5, L_TOML,
    L_EXTERNAL };

#define NPPMSG (WM_USER + 1000)

// Plugin notifications (nmhdr.code values received by beNotified)
#define NPPN_FIRST 1000
#define NPPN_READY (NPPN_FIRST + 1)
#define NPPN_TBMODIFIED (NPPN_FIRST + 2)
#define NPPN_FILEBEFOREOPEN (NPPN_FIRST + 3)
#define NPPN_FILEOPENED (NPPN_FIRST + 4)
#define NPPN_FILECLOSED (NPPN_FIRST + 5)
#define NPPN_FILEBEFORESAVE (NPPN_FIRST + 6)
#define NPPN_FILESAVED (NPPN_FIRST + 7)
#define NPPN_SHUTDOWN (NPPN_FIRST + 8)
#define NPPN_BUFFERACTIVATED (NPPN_FIRST + 9)
#define NPPN_LANGCHANGED (NPPN_FIRST + 10)
#define NPPN_DARKMODECHANGED (NPPN_FIRST + 15)

#define NPPM_GETCURRENTSCINTILLA (NPPMSG + 4)
#define NPPM_GETCURRENTLANGTYPE (NPPMSG + 5)
#define NPPM_SETCURRENTLANGTYPE (NPPMSG + 6)
#define NPPM_GETNBOPENFILES (NPPMSG + 7)
#define NPPM_GETCURRENTDOCINDEX (NPPMSG + 23)
    #define MAIN_VIEW 0
    #define SUB_VIEW 1
#define NPPM_GETCURRENTBUFFERID (NPPMSG + 60)
#define NPPM_GETFULLPATHFROMBUFFERID (NPPMSG + 58)
#define NPPM_GETBUFFERLANGTYPE (NPPMSG + 64)
#define NPPM_GETNPPVERSION (NPPMSG + 50)
#define NPPM_GETPLUGINSCONFIGDIR (NPPMSG + 46)
#define NPPM_MENUCOMMAND (NPPMSG + 48)
#define NPPM_SETMENUITEMCHECK (NPPMSG + 40)

// Notepad++ menu command id (from menuCmdID.h) — used to open a new document.
#define IDM_FILE_NEW 41001

// Dockable dialog messages
#define NPPM_DMMREGASDCKDLG (NPPMSG + 33)
#define NPPM_DMMSHOW (NPPMSG + 30)
#define NPPM_DMMHIDE (NPPMSG + 31)
#define NPPM_DMMUPDATEDISPINFO (NPPMSG + 32)
